name: python app test with Github Actions

on: [push]

jobs:
  build:

    runs-on: ubuntu-lastest
    
    steps:
    - uses: actions/checkout@v2

    - name: setup python 
      uses: actions/setup-python@v1

      with:
        python-version: 3.8

    - name: install dependencies
      run: make install

    - name: Lint with pylint
      run: make lint
    - name: test with pytest 
      run: make test 
    - name: format code
      run: make format 
      
      
      

